### numpy的引入，是因为它的ndarray 计算效率要大大优于python自身的数组计算

In [1]:
import numpy as np

#### numpy的核心当然就是ndarray了，这里主要介绍5个创建多维数组ndarray的方法，

In [2]:
#将二维数组转换为 ndarray
a1 =  np.array([[1,2,3],[4,5,6]])
a1   

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a2 = np.ones((2,3)) #第二种生产ndarray的方法 也可以np.zeros((2,3))
a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
a3 = np.random.randn(3,4) #第三种生产ndarray的方法， 生产3行四列的，值服从标准正太分布 即均值为0 方差为1的正太分布
print(a3)

[[-1.36354275 -0.5966398  -0.72543125  0.77659946]
 [-0.44147671 -0.61100333 -0.45587871  0.19609401]
 [ 0.98445832 -0.35537209 -0.22235292 -1.23798767]]


In [16]:
a4 = np.random.rand(2,5) #第四种生产ndarray的方法，生产的数在 [0,1)之间
a4

array([[0.65240337, 0.17189447, 0.70986102, 0.5304766 , 0.16295904],
       [0.4136444 , 0.68882999, 0.49697891, 0.79412349, 0.97252221]])

In [18]:
a5 = np.random.randint(1,5,size=(2,3)) #第5中生产ndarray的方法，其中参数的前两个制定，数值的范围，这里[1,5)之间的整数，维度通过size =()来指定
a5

array([[3, 2, 2],
       [1, 1, 2]])

In [21]:
np.empty((2,5)) #这里有点坑要注意，看起来empty似乎是值都为空，但其实里面都是有随机数的

array([[0.65240337, 0.17189447, 0.70986102, 0.5304766 , 0.16295904],
       [0.4136444 , 0.68882999, 0.49697891, 0.79412349, 0.97252221]])

#### 重要的属性和方法

In [6]:
#最重要的一个属性shape 查看ndarray的维度,这里是二行三列
a1.shape

(2, 3)

In [30]:
# reshape改变ndarray 的维度 ，这里有一个trick 可以使用 -1 让np去自动计算维度
a6 = np.random.rand(2,6).reshape(3,4)
a6

array([[0.94480792, 0.3042592 , 0.54590056, 0.95874383],
       [0.99466323, 0.8596527 , 0.97232934, 0.19828298],
       [0.77289658, 0.55684268, 0.01365015, 0.15260889]])

In [31]:
a6.reshape(6,-1)

array([[0.94480792, 0.3042592 ],
       [0.54590056, 0.95874383],
       [0.99466323, 0.8596527 ],
       [0.97232934, 0.19828298],
       [0.77289658, 0.55684268],
       [0.01365015, 0.15260889]])

#### ndarray的运算

In [14]:
#numpy的 ndarray 具有广播性质 加减乘除操作 会广播到每个元素
a1 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [13]:
a1+a2 #对应元素相加

array([[2., 3., 4.],
       [5., 6., 7.]])

In [23]:
a1 +a3  #这里报错，是因为两个ndarray 维度不一致，无法加法操作。可见 加减法必须两个ndarray维度一致

ValueError: operands could not be broadcast together with shapes (2,3) (3,4) 

In [25]:
a1.shape ,a3.shape

((2, 3), (3, 4))

In [26]:
a1.dot(a3)  #数组的点乘，相当于矩阵乘法 要注意维度，不满足矩阵乘法要求，会报错

array([[ 0.70687878, -2.88476275, -2.30424743, -2.54517553],
       [-1.75480465, -7.57380843, -6.51523605, -3.34105812]])

#### ndarray的数据访问

In [44]:
#索引访问
b1 = np.zeros((8,5))
for i in range(b1.shape[0]): #对第i行全部赋值为i
    b1[i] = i
print(b1)
print('--------------')
print(b1[[1,3,5]])


[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7.]]
--------------
[[1. 1. 1. 1. 1.]
 [3. 3. 3. 3. 3.]
 [5. 5. 5. 5. 5.]]


In [45]:
#切片访问，获取前三行，前两列的数据
b1[1:4,0:2]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [53]:
# 第三种，布林indexing 
b1[ b1>3] #返回的是一个一维的数组

array([4., 4., 4., 4., 4., 5., 5., 5., 5., 5., 6., 6., 6., 6., 6., 7., 7.,
       7., 7., 7.])

#### 数学统计运算

In [55]:
b1.T #矩阵转置

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [58]:
np.mean([1,2,3])

2.0

In [61]:
b1.mean(),b1.max(),b1.min()

(3.5, 7.0, 0.0)

- np.where(condition, x, y)  满足条件(condition)，输出x，不满足输出y。

In [65]:
# 数据批量处理
arr = np.random.randn(4, 4)
print(arr)
print('--------分隔符------------')
print(np.where(arr > 0, 2, -2))  #数组arr中 满足大于0的元素返回2 否则返回-2

[[-0.15876871 -0.16046074 -0.02669914  0.1132621 ]
 [-0.5778095  -2.09169431 -1.08367755 -1.2121039 ]
 [ 0.78598575  1.04984935  1.68057298  0.60049314]
 [-0.26390488 -1.07360506  0.12752369  1.51414237]]
--------分隔符------------
[[-2 -2 -2  2]
 [-2 -2 -2 -2]
 [ 2  2  2  2]
 [-2 -2  2  2]]


### pandas

- 有两种数据结构 series 和 dataframe ,前者是一维的，相当于一维数组。 后者是二维的，相当于一张表格